require 'opal'
require 'opal-activesupport'
require 'jquery'
require 'browser'
require 'vienna'
require 'opal-jquery'
require 'electron/fixtures'
require 'electron/wrapper'
require 'electron/wrapper_class'
require 'electron/observable'
require 'electron/window'
require 'electron/renderer_process_modules'
require 'electron/both_process_modules'

